name: Build SunamoMail

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoMail
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMail/SunamoMail.csproj

    - name: Build
      run: dotnet build SunamoMail/SunamoMail.csproj --configuration Release --no-restore

  test:
    name: Test SunamoMail.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMail.Tests/SunamoMail.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoMail.Tests/SunamoMail.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoMail.Tests/SunamoMail.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
